/**
  *
  *
  * Information::Transfer
  *
  *  :0
  *
  *
  *
 **/

class IT Insert NerveGear.NBP{
  
    Input(1)-;
    Input(2)-;
    Input(3)-;
    Input(4)-;
    Input(5)-;
    Input(arrays(...))-;
    Output(arrays(1,2,3,4,5,...))-;
   Strem::( @Input(1)==?1 ,@Input(2)==?2 ,@Input(3)==?3 ,@Input(4)==?4 ,@Input(5)==?5 ,@Input(arrays(...))==!arrays?...
)-{
     ?1 push AI::Nerve#Numbers%3{
       Click*Click*Transfer*Nano*(Open(Close(Open(Close(Continue)))))::Insert ?1
}





